version: '3'
services:
   wordpress:
    build: .
    ports:
      - ${WORDPRESS_PORT}:80
      - ${WORDPRESS_SSLPORT}:443
    volumes:
      - ./app/public/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_ENV: development
   mysql:
    image: mysql
    ports: 
      - ${MYSQL_PORT}:3306
    environment: 
      MYSQL_ROOT_PASSWORD: example
   mailhog:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_ADMIN_PORT}:8025
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}