version: '3'
services:
   wordpress:
    build: .
    ports:
      - ${WORDPRESS_PORT}:80
      - ${WORDPRESS_SSLPORT}:443
    volumes:
      - ./app/public/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}